spring:
  application:
    name: demorg

  data:
    mongodb:
      uri: mongodb+srv://rahulgoyal28695:India%401234@cluster0.6qvily3.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: journaldb

  main:
    allow-circular-references: true

server:
  port: 8081
  servlet:
    context-path: /journal


